### ISSUE TITLE
can't log into dev portal

### ISSUE THREAD

**Issue by dannyob** [worldcoin/developer-portal#356]
I'm on iPhone (iOS 16.5.1) and while clicking on the login/signup buttons takes me to the World App, nothing happens after that, just the standard World App home page showing the faux identity card.

**Comment by arun1940** [comment]
The same issue, I am facing. I have verified the phone number, but still, I cannot log in. I am getting errors with code 4800 or sometimes different on the app.

**Comment by pdtfh** [comment]
you can now log in to the developer portal with your email address
