### ISSUE TITLE
Validation error for Orb Operator form

### ISSUE THREAD

**Issue by pnoken** [worldcoin/developer-portal#390]
Form can be found [here](https://worldcoin.org/be-a-worldcoin-operator). Entering 8 digits gives correct validation instead of 9 digits.

![image](https://github.com/worldcoin/developer-portal/assets/64193869/8effe68d-2ea8-41d7-8299-5d327bf44fb0)

**Comment by pdtfh** [comment]
hey @pnoken, please contact support for help with this form
