### ISSUE TITLE
Signing in on Mobile Device results in "Invalid Link"

### ISSUE THREAD

**Issue by erados** [worldcoin/developer-portal#760]
Even in the developer portal (https://developer.worldcoin.org/), I cannot sign in on mobile devices.

I am unsure whether this issue is due to the app source code or the developer portal route (`api/v2/verify`).

For your reference, I have attached a video recording of the issue below.

https://github.com/worldcoin/idkit-js/assets/19205043/1d160eb8-ebc7-4bb4-9ef2-c35a5f83d82e

**Comment by andy-t-wang** [comment]
Should be fixed!
